channels:
- conda-forge
dependencies:
- python
- ipython
- pip
- notebook
- numpy
- pandas
- matplotlib
- xarray
- netcdf4
- scipy
- cartopy
- jupyterlab
- pip:
  - cdsapi
  - holoviews
  - itables
  - jupytercards
  - jupyterquiz
name: cds-environment
