name: cds-environment
dependencies:
  - bokeh
  - cartopy
  - cdsapi
  - coreapi
  - dask
  - folium
  - geoviews
  - holoviews
  - hvplot
  - geopandas
  - json
  - jupytercards
  - jupyterlab
  - jupyterquiz
  - leafmap
  - matplotlib
  - micropip
  - netCDF4
  - numpy
  - os
  - pandas
  - xarray
  - zipfile
  
